typography_spectrum: 0.7213756605051458
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7072547578718513
  lightness: 0.6866912874393165
  saturation: 0.10702915745787323
  rhythmicContrast: 0.8619810219388455
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.11048357863910496
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Rolff
  email: rolff@blackbirdstudio.com
  url: blackbirdstudio.com
name: Blackbird Studio
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Recording Studio
purpose: []
