name: Blackbird Studio
favicon: null
layout_spectrum: 0.11048357863910496
typography_spectrum: 0.7213756605051458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7072547578718513
  lightness: 0.6866912874393165
  saturation: 0.10702915745787323
  rhythmicContrast: 0.8619810219388455
purpose: []
